name : Continuous Delivery
on: 
  push:
    branches:
      - main # ou qualquer branch que você queira monitorar para deploy

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuos Delevery
        uses: actions/upload-artifact@v7
        with:
          name: projetozipado.zip
          path: |
            '**.java'
            README.md