name: Continuous Delivery

on:
  push:
    branches:
      - main # ou qualquer branch que você queira monitorar para deploy

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            **/*.java
            README.md

  docker:
    needs: deliver
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4