name: 'OpenCommit Action'

on:
  push:
    branches-ignore: [main, master, dev, development, release]

jobs:
  opencommit:
    timeout-minutes: 10
    name: OpenCommit
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # - uses: di-sukharev/opencommit@github-action-v1.0.4
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   env:
      #     OCO_OPENAI_API_KEY: ${{ secrets.OCO_OPENAI_API_KEY }}
      #     OCO_TOKENS_MAX_INPUT: 4096
      #     OCO_TOKENS_MAX_OUTPUT: 500
      #     OCO_OPENAI_BASE_PATH: ''
      #     OCO_DESCRIPTION: false
      #     OCO_EMOJI: false
      #     OCO_MODEL: gpt-4o
      #     OCO_LANGUAGE: en
      #     OCO_PROMPT_MODULE: conventional-commit

  docker:
    needs: opencommit
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4